### ISSUE TITLE
IterativeAssembler and mapping

### ISSUE THREAD

**Issue by anands-repo** [Illumina/strelka#117]
Hi,

I was going through how the iterative assembler decides the supporting reads of a contig. My understanding is that a read deviating from a contig's sequence of bases (supporting an alternative base or allele) is considered a rejected read, which is then not considered to be mapped to the contig. Please correct me if wrong.

Does this mean that a read with a sequencing error is considered a rejected read from a contig's perspective? Then it means that the top contigs are decided based solely on noise-free reads. Is this correct? If so, this seems quite surprising because more than a few reads may be discarded in determining the top two contigs, and it still works!.

Please correct me if my understanding is wrong.

Thanks!

**Comment by sangtaekim** [comment]
Sorry for the long delay. There was miscommunication between different teams.

Your description is correct and it is true that the determination of the top two contigs (or haplotypes) is rather empirical. 

Strelka still works well because this haplotyping stage is mainly for determining "candidate indels" which are refined later using a more sophisticated scoring scheme. When we actually scoring SNVs and indels, those reads (discarded in haplotyping) are also used with other reads.

**Comment by anands-repo** [comment]
Thanks for the response! It is very helpful to have confirmation.
