### ISSUE TITLE
TAR > DP in vcf file for some indels

### ISSUE THREAD

**Issue by danielbruhm** [Illumina/strelka#118]
I'm running the Strelka v2.9.0 somatic workflow and I've noticed that in a subset of the reported indels the read depth for tier1 (DP) is less than the reads strongly supporting alternate allele for tiers 1,2 (TAR). I'm wondering how the number of reads supporting the alternate allele can be greater than the read depth?

Here's an example variant call from the vcf file that has TAR > DP (it is also greater than DP2):

`chr9	21991052	.	CATAG	C	.	PASS	SOMATIC;QSI=46;TQSI=1;NT=ref;QSI_NT=46;TQSI_NT=1;SGT=ref->het;MQ=254.00;MQ0=0;RU=ATAG;RC=2;IC=1;IHP=2;SomaticEVS=17.18	DP:DP2:TAR:TIR:TOR:DP50:FDP50:SUBDP50:BCN50	16:16:17,17:0,0:0,0:16.78:0.00:0.00:0.00	53:53:38,39:13,13:3,3:49.91:0.00:0.00:0.00`

**Comment by sangtaekim** [comment]
This is undesirable but may happen very rarely because the way Strelka2 calculates DP and TAR/TIR is different. DP is the count of the pile-up bases at the indel position - 1 based on optimal alignments of reads. TAR/TIR is calculated considering multiple high-scoring alignments of each read. Thus for some reads, the alignment used for counting DP may different from the alignments used for counting TAR/TIR so are their start/end positions and this weird thing may happen. My recommendation is to simply ignore it.

**Comment by danielbruhm** [comment]
Got it, thank you for clarifying.
