### ISSUE TITLE
Trouble reading VCF file with --ploidy option 

### ISSUE THREAD

**Issue by afkoeppel** [Illumina/strelka#25]
Hi there,

I'm doing some variant calling on mitochondrial reads, and I want to specify that the MT chromosome is haploid using the --ploidy argument.

The config script runs fine, but the workflow script is failing to read the vcf file.  My vcf file is attached (I set it up based on the example on the README).

[CallGenome+callGenomeSegment_chromId_000_1_0013] ERROR: Failed to load header for VCF file: '/data/nextseq-validation/benchmark-mito/benchmark_afk/ploidy_MT.vcf.gz'

Thanks,
Alex Koeppel

P.S.  My apologies if I've just made an error creating the VCF file.  I tried a number of different modifications but all resulted in the same error.

[ploidy_MT.vcf.gz](https://github.com/Illumina/strelka/files/1483510/ploidy_MT.vcf.gz)

@stephenturner

**Comment by ctsa** [comment]
Thanks for the inquiry. Looks like an extra space in the header field " POS"

```
vcf-validator ploidy_MT.vcf.gz
The column name contains leading/trailing spaces, removing: ' POS'
```

By the way, I recommend the option `--callContinuousVf MT` instead (this is what we use in-house). This selection will make all calls on MT without a ploidy assumption, based on a rough assessment of which alternate allele frequencies exceed the background noise level. I should warn you up front that this model is still very rough (we are working on improvements) -- nonetheless the result should be more useful than the ploidy=1 model because it will give you access to most of the heteroplasmic variants. Also note that unlike using the ploidy VCF file the `--callContinuousVf` option cannot be made per-sample -- it is assumed that you will select continuous calling for a chromosome in all samples.

**Comment by ctsa** [comment]
BTW we switched the user guide VCF examples to use literal tabs so that they copy/paste correctly (in next patch update).

**Comment by afkoeppel** [comment]
Thanks so much for your help in discovering my vcf issue.  I didn't know about vcf-validator but I will make sure to use it in the future.

Thanks also for the tip about --callContinuousVf.  I tried this and it caught all same MT variants that ploidy=1 did, as well as the heteroplasmic variants you referred to.
