### ISSUE TITLE
Strelka2 crashes on targeted sequencing experiment

### ISSUE THREAD

**Issue by PedroBarbosa** [Illumina/strelka#32]
Hello,

I've read your guide, and I knew beforehand that strelka2 is not intended to run germline analysis in a larger scale. Anyway, I decided to give it a try (I have a set of around 800 case samples for a small panel of 40 genes), and I would like to know if the error I'm facing has to do with this known limitation, or may it be something else I'm missing.

Please find attached the last 50 lines of log of the run. (Full log is 35Mb big)
[strelka2.log](https://github.com/Illumina/strelka/files/1728943/strelka2.log)

Thanks in advance,
Best,
Pedro

**Comment by ctsa** [comment]
Do I understand correctly that you attempted joint analysis for 800 samples?

It's hard to tell from the log tail, but it looks like you've hit some kind of limit to the number of files which can be opened by a single process (or -- somewhat less likely -- a per-directory file count limit)? The error messages are from individual variant calling processes which are failing to open new VCFs for writing variant calling results to. Since strelka2 isn't currently optimized for high sample counts, if you run 800 samples it will attempt to open 800 (+ a few more) files for output all at once -- so this seems like a plausible cause of failure.

If you really want to push the sample count limit you might be better off trying joint analysis of 50-100 samples -- but, per the docs, sample counts beyond "family-scale" (which we define as 10 or fewer) are not tested.

**Comment by PedroBarbosa** [comment]
Yes, that's it.
Full log can be accessed [here.](https://www.dropbox.com/s/zb6kbnu79zu8a5q/59921_strelka2.log?dl=0) It also includes messages from the slurm scheduler.


I'm running now strelka2 in batches of 75 samples. So far, everything ok. Is it ok to combine all the gVCFs at the end ?

**Comment by ctsa** [comment]
To combine the gVCFs at the end of the process, you might want to check on the recently pushed gvcfgenotyper project here:

https://github.com/Illumina/gvcfgenotyper

I'm not sure if this will work for your targeted data case -- Any advice on this, @jaredo?

**Comment by jaredo** [comment]
Thanks Chris, I think it will work (although we have never tried with gene panels before). 

@PedroBarbosa please get in touch if you want to try it out.

**Comment by PedroBarbosa** [comment]
@ctsa , 2 out of 12 jobs failed.  Maybe 75 samples is still too much ? 
[workflow.error.log.txt](https://github.com/Illumina/strelka/files/1736335/workflow.error.log.txt)

I want to try it @jaredo, will get in touch when all the variants are called.

**Comment by ctsa** [comment]
Based on the error message it looks like a random system resource shortfall. I suggest just running the `runWorkflow.py` command again for the two failed jobs (it will pick right back up from the point of interruption).

**Comment by PedroBarbosa** [comment]
It wored out @ctsa , thanks.

Will proceed now with the gvcfgenotyper phase. @jaredo

**Comment by ctsa** [comment]
Sounds good, will close this ticket then.
