### ISSUE TITLE
about Hard filtering in strelka2

### ISSUE THREAD

**Issue by Maojie6509** [Illumina/strelka#46]
Hi, chris

Ⅰ. When I checked these "PASS" results,  I found some  QSS_NT or QSI_NT flags of some variants ( SNP or INDEL)   are a constant 3070 , Does those variants should be filtered out ? and I wondered  the formula for these  parameters ? 
Ⅱ. I want to do some Hard filter after I got the variants results with Strelka2 ,But can not found 
SiteFilteredBasecallFrac , SpanningDeletionFraction and IndelWindowFilteredBasecallFrac parameters in the VCF FORMAT, I do not know how to do this filter?

Thanks a lot

**Comment by ctsa** [comment]
Sorry for the delay. QSI_NT is mostly computed as in strelka1. A high constant value indicates that a highest computable value has been reached -- there's probably not much information in QSI_NT over about 100, but we leave a large range above that point because the rank information can be useful.

Instead of using QSI_NT directly, strelka2 uses this score as one input to its empirical scoring (EVS) module which is ultimately used to pass variants. You can see the supplement of our pre-print for details (http://dx.doi.org/10.1101/192872)

The output has been configured for automated pipelines so mostof the EVS features are not output by default. If you want to see all of the features used by the scoring model (in addition to experimental scoring features), you can enable the `--reportEVSFeatures` scoring option as described here:

https://github.com/Illumina/strelka/blob/master/docs/userGuide/trainingSomaticEmpiricalScore.md#step-1-build-a-training-data-set
