### ISSUE TITLE
Difference of somatic InDel results between strelka and strelka2

### ISSUE THREAD

**Issue by zhangnan0107** [Illumina/strelka#57]
Hi, 
I have recently tried Strelka2 to detect somatic InDels, first please accept my thanks for this convenient program, however, I think I unfortunately got a confusing problem which might due to my incorrect settings or command line. Here is what I did, I used both Strelka and Strelka2 to call InDels from a paired-BAM(Normal&Tumor) files, and strelka can successfully detect a deletion mutation which is known to be existed in the sample, but strelka2 even didn't show any potential InDels. In the command line I just provided 2 BAMs, reference, and Manta candidate. I also tried without Manta candidate, the results are the same. To double check if the reason is because my settings or command line, another 5 samples were tested, and 3 of them also have the similar situation, that is strelka2 did not detect some InDels which occurred in strelka. So I want to know if there are some configure parameters need to be modified before running, or did you compare the results between strelka and strelka2, if yes how was that?

Attached are the snapshots of strelka and strelka2, just for convenient.

Thanks
Nan

![strelka](https://user-images.githubusercontent.com/34366426/43312169-13ed3f16-91bf-11e8-8fd3-ee96b22ba29e.PNG)
![strelks2](https://user-images.githubusercontent.com/34366426/43312170-14300896-91bf-11e8-845c-b8a05d3baee3.PNG)

**Comment by ctsa** [comment]
Thanks for reporting your observations. For the two examples you provide screenshots for above, could you include strelka vs strelka2 output for the same locus? The above appears to be strelka1 output from from one locus and strelka2 output from a second one.

**Comment by zhangnan0107** [comment]
Sure, no problem, and sorry for that I didn't explain the above screenshots clearly, the above one that just contains one locus is from strelka1 (indels.passed.vcf), and the bottom one in which all chromosomes start with "GL" is from strelka2, however, both of them are from the same paired BAM file, that is why I got confused because there are no overlap between the results from 1 and 2.

Here are another screenshots from strelka1 and strelka2 for the same locus.
![strelka1](https://user-images.githubusercontent.com/34366426/43374053-4cdc9d58-93e0-11e8-9adf-df988a9db349.png)
![strelka2](https://user-images.githubusercontent.com/34366426/43374056-5372f540-93e0-11e8-9afd-93847650a6ea.png)

**Comment by ctsa** [comment]
Thanks for sharing the additional detail.

This looks like exome data. If so, could you try rerunning strelka2 with the `--exome` flag?

**Comment by zhangnan0107** [comment]
It works! Thanks so much Chris! The result looks like much more satisfying with providing a detection region with `--callRegions` and `--exome` flags, thanks again! 

So it seems this flag is actually a critical factor? I thought there would be more callings without restriction to a specific region.

And another question, do you have any recommended protocol about filtering the results by FILTER flag in vcf file, I mean will that be better to extract just PASS mutations? Or I can also consider those indels not labeled by PASS, you know, like HighDepth in the above picture?

**Comment by ctsa** [comment]
The `--exome` flag is very important because Strelka by default will look for regions which have anomalously high depth compared to the chromosome median depth (of the normal sample), and filter those out. This makes sense in the WGS context where we want to reduce confidence in calls made within reference compressions, etc.. but should not be applied to exome or targeted data. I believe that was causing the issue for your analysis.

The PASS calls should be the best starting point. The recommended way to explore the precision-recall curve is to look at different thresholds of the SomaticEVS score -- which is the final somatic variant score incorporating all somatic features. There is a script provided for convience to quickly change the PASS threshold with respect to different somaticEVS values here:

https://github.com/Illumina/strelka/blob/master/scratch/util/reFilterSomaticVcf.py

**Comment by zhangnan0107** [comment]
I see, thanks a lot for the helping and suggestion.

Best,
Nan
