### ISSUE TITLE
Difference between Strelka2 INDELs with BED and without

### ISSUE THREAD

**Issue by looxon93** [Illumina/strelka#64]
Hi,

I started using Strelka2 (2.8.3) like you suggested in manual. I gave T/N BAM files, Manta small indel candidates and BED file. What I noticed that for INDELs contents of files are different when I use BED file on input and when I don't provide BED input but I later intersect VCF file with that BED keeping only mutations that are in BED region file. For SNPs everything seems to be ok.

When I provide BED number of lines (without header) I get is: 2652 of which 1111 are PASS mutations.
When I don't provide BED but intersect INDEL output with it I get: 2667 of which 1124 are PASS mutations.

I expected those two to be the same. Also content of file is different, SAMPLE fields can be different to be precise. Here are examples of lines (first is from run with BED, second is just intersected):

`1	52179818	.	GT	G	.	LowEVS	SOMATIC;QSI=42;TQSI=1;NT=ref;QSI_NT=42;TQSI_NT=1;SGT=ref->het;MQ=59.70;MQ0=0;RU=T;RC=12;IC=11;IHP=13;SomaticEVS=3.33	DP:DP2:TAR:TIR:TOR:DP50:FDP50:SUBDP50:BCN50	29:29:18,20:0,0:9,7:51.85:1.47:0.00:0.02	81:81:38,41:12,14:28,23:129.11:5.75:0.00:0.04`

`1	52179818	.	GT	G	.	LowEVS	SOMATIC;QSI=42;TQSI=1;NT=ref;QSI_NT=42;TQSI_NT=1;SGT=ref->het;MQ=59.70;MQ0=0;RU=T;RC=12;IC=11;IHP=13;SomaticEVS=3.33	DP:DP2:TAR:TIR:TOR:DP50:FDP50:SUBDP50:BCN50	29:29:18,20:0,0:9,7:33.98:1.31:0.00:0.03	81:81:38,41:12,14:28,23:89.51:4.93:0.00:0.04`

Do you have some explanation for this behaviour? I thought that Strelka2 algorithm look at whole region and then just keeps variants that are in given BED regions? 

Thanks,
Luka.

**Comment by ctsa** [comment]
Sorry for the delay. The terms that differ between the two calling protocols, 'DP50:FDP50:SUBDP50:BCN50' are all computed from windows extending 50 bases upstream and downstream of the variant position. It seems plausible that this difference could be occurring for calls within 50 bases of the a bed region boundary, because Strelka would either be treating the input depth as zero in off target regions for the purpose of computing these metrics or using a smaller window, bounded by the target region.

This sounds like a flaw in Strelka's `callRegion` design -- which is intended, as you suggest, to provide the same calls within targeted regions whether or not the callRegion bed file is specified. I will open a new ticket for this case.
