### ISSUE TITLE
Somatic AF 0%

### ISSUE THREAD

**Issue by ATpoint** [Illumina/strelka#65]
I am calculating the allele frequencies from a somatic VCF that was produced with the default settings on a hg38 matched-normal WGS pair:

`configureStrelkaSomaticWorkflow.py --normalBam={}-n_SortedRmdup.bam --tumorBam={}-t_SortedRmdup.bam --callRegions=primary_chromosomes.bed.gz --runDir=Strelka2Dir_{} --referenceFasta=hg38.fa`

Following the recommendation for AF calculation (https://github.com/Illumina/strelka/blob/master/docs/userGuide/README.md#somatic), I extract the necessary information, but noticed for this line an AF of 0, because the ALT count (nucleotide A) for tier1 is 0. Could you comment on that? If you need further information, please specify your needs.

`chr1	122551300	.	G	A	.	PASS	SOMATIC;QSS=48;TQSS=2;NT=ref;QSS_NT=48;TQSS_NT=2;SGT=GG->AG;DP=360;MQ=10.98;MQ0=243;ReadPosRankSum=-2.4;SNVSB=0;SomaticEVS=9.02	DP:FDP:SDP:SUBDP:AU:CU:GU:TU	22:1:0:0:0,8:0,0:21,158:0,0	15:1:0:0:0,9:0,0:10,181:4,4`

**Comment by ctsa** [comment]
Thanks for reporting this case. It definitely appears to be a problematic call. Something in the call mechanism might not be working as intended due to the tri-allelic event (this shouldn't be a problem in theory) -- if anything the call might be: GG->GT

Would you be able to share a slice of the bams around this region? ...or failing that would it be possible to get an IGV view?

**Comment by ATpoint** [comment]
Thank you for the immediate reply. I uploaded the requested BAM files (1000bp left and right of the event) to [ our cloud here](https://uni-muenster.sciebo.de/s/cZyykLkWCvM1qzm).

**Comment by ctsa** [comment]
Thank you. Reference chromosome ordering in these BAMs appears to be a bit different than any standard I can point to, would you mind uploading the reference fasta as well to save us some time?

**Comment by ATpoint** [comment]
Of course. You find it under the same link.

**Comment by ctsa** [comment]
Thanks, pulling it down now.

**Comment by ctsa** [comment]
HI, sorry for the delay. It looks like this position is called as a 'tier2' variant -- although what we're seeing here is not a bug, it is obviously not ideal behavior -- both in the sense that the surrounding context for this call is relatively noisy, and they way it is communicated in the VCF is confusing, given that this makes things like the variant allele frequency hard to reason about.

Since passed 'tier2' calls should be rare, the best practical suggestion I can make for the sort term would be to consider filtering out the PASS'd tier2 calls (ie. calls with `TQSS_NT=2`) from your calculation.

**Comment by ATpoint** [comment]
Thank you Chris for the response and suggestion. Just another thing that is a bit off-topic here: Do you know if Canvas is still under active maintanance? I raised an issue there about a week ago (which is of course not a long time, so I do not want to complain or anything) but was just wondering if it has a chance to be answered.

**Comment by ctsa** [comment]
Re: Canvas - thanks for inquiring . Issue response has been complicated by leave status. We're discussing improvements to delegation and bot-messaging for these projects to make open-source support a bit more predictable.
