### ISSUE TITLE
Impact of not pre-running Manta on somatic indels calls  

### ISSUE THREAD

**Issue by Sames-Jtudd** [Illumina/strelka#72]
Hi,

I've run Strelka2 on 300 WGS sample pairs and called SVs and indels. I didn't use the candidate indels input created by running Manta first. 

In the Strelka2 documentation it says that this is recommended but not necessary. If you could elaborate on what is meant by this I be grateful. What are the potential consequences for indel output of not calling Manta first?  

Due to the cohort size Id rather not run again if unnecessary. 

Also is there a list of common sequencing artefacts that are filtered out as standard using the EVS score, in the documentation for example it mentions strand bias, so I assume that oxoG artefacts should be removed with this filter?
I cant see any reference to homopolymer context of mutations are these also dealt with with the EVS score?

Many thanks

**Comment by sangtaekim** [comment]
Hi @Sames-Jtudd ,

Glad to hear that you ran Strelka for your cohort analysis!

In somatic calling, we recommend to provide Manta indel candidates to improve Strelka's sensitivity to call long (e.g. >20) indels. Unlike its germline caller, Strelka's somatic caller does not employ haplotyping/local assembly and thus may miss some long indels that are not well represented in the input alignment file. Manta provides candidate indels that may have been missed by Strelka. In our test data, the fraction of such indels is very low. Therefore, if you are not particularly interested in long indels, I believe you won't need to rerun Strelka.

We don't have a list of common sequencing artefacts. Instead of handling individual artefacts, we designed EVS to mitigate them through features. The strand bias feature (TumorSampleStrandBias) would mitigate the oxoG artefacts and the InterruptedHomopolymerLength feature would count in homopolymer contexts. The complete list of somatic EVS features is in the Supplementary Note 1.3.2 of the Strelka2 publication (https://www.nature.com/articles/s41592-018-0051-x). You may also find them in the Strelka method documentation at https://github.com/Illumina/strelka/tree/master/docs/methods/primary.

**Comment by Sames-Jtudd** [comment]
thanks very much of the prompt and complete answer.
